package com.example.memory.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Builder;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "Snapshot")
@Builder
public class Snapshot {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String timestamp;

    @DynamoDBAttribute
    private String videoUrl;

    @DynamoDBAttribute
    private String imageUrl;

}
